version: "3.7"

services:
  video-chat:
    build:
      context: .
      dockerfile: Dockerfile
    image: video-chat
    container_name: video-chat
    restart: unless-stopped
    networks:
      - app-network
    # ports:
    #   - "9910:9910"
  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    depends_on:
      - video-chat
    networks:
      - app-network
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email test@test-server.space --agree-tos --no-eff-email --staging --force-renewal -d test-server.space  -d www.test-server.space

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /root/projects/video-chat-rooms/video-chat-room-backend/views/
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /root/projects/video-chat-rooms/dhparam/
      o: bind

networks:
  app-network:
    driver: bridge

#https://www.digitalocean.com/community/tutorials/how-to-secure-a-containerized-node-js-application-with-nginx-let-s-encrypt-and-docker-compose