version: "3.7"

services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./video-chat-room-backend
    ports:
      - "9910:9910"
    expose:
      - 9910
    restart: always
#
#  frontend:
#    build:
#      dockerfile: Dockerfile
#      context: ./../studia-poland-webapp
#    ports:
#      - "3000:3000"
#    expose:
#      - 3000
#    restart: always
#    depends_on:
#      - backend